# Generated by Django 4.0.4 on 2022-04-18 14:05

from django.db import migrations, models
import tool.helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('month', models.DateField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('header_row', models.IntegerField(default=1, verbose_name='Numéro de ligne où sont contenus les titres de colonnes (si vide = 1)')),
                ('profile', models.CharField(choices=[('CLI', 'Client'), ('TRP', 'Transporteur')], default='Client', max_length=100, verbose_name='Choix du profil')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', validators=[tool.helpers.validate_file_extension])),
            ],
            options={
                'verbose_name': 'file',
                'verbose_name_plural': 'files',
            },
        ),
    ]
